# Generated by Django 3.2.8 on 2021-10-15 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.categorie')),
            ],
        ),
    ]
