# Generated by Django 3.2.8 on 2021-10-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('Sport', 'Sport'), ('sante', 'Santé'), ('Politique', 'Politique')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
