# Generated by Django 3.2.8 on 2021-10-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20211015_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('Sport', 'sport'), ('sante', 'santé'), ('Politique', 'politique')], max_length=30),
        ),
    ]
